<a href="https://colab.research.google.com/github/emignox/fundamentals-tensorflow/blob/main/00fundamentals_tensorflow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#import tensorFlow
import tensorflow as tf
print(tf.__version__)

2.15.0


In [ ]:
# create tensor with tf.constant
scalar  = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [ ]:
#number of dimensions of a tensor
scalar.ndim

0

In [ ]:
vector = tf.constant ([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [ ]:
# check dimension of our vector
vector.ndim

1

In [ ]:
#create a metrix has more than 1 dimension
matrix = tf.constant([[10,7],[7,10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [ ]:
matrix.ndim

2

In [ ]:
#create another matrix
another_matrix = tf.constant([[10.,7.],[3.,2.],
                              [8.,9.]],dtype=tf.float16)
another_matrix
#specify the data type  with dtype parameter

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 8.,  9.]], dtype=float16)>

In [ ]:
#number of dimension
another_matrix.ndim

2

In [ ]:
# let's create a tensor
tensor = tf.constant([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]],[[13,14,15],[16,17,18]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [ ]:
tensor.ndim

3

what we create so far:
*  scalar : a single number
* vector : a number with direction (e.g wind speed and direction)
* matrix: a 2 dimensional array of numbers
* tensor:an n dimensional array of numbes (wher en can be any number,
                                          a 0-dimensional tensor is a scalar , a 1-dimensional tensoro is vector)

In [ ]:
#create the same tensor  with a tf.variable
changeable_tensor = tf.Variable([10,7]) # deve essere scritto con V maiuscola variable
unchangeble_tensor = tf.constant ([10,7])
changeable_tensor,unchangeble_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [ ]:
#let's try change one of the elements in our changeble tensor
##changeable_tensor[0]= 7
##changeable_tensor

#right way
changeable_tensor[0].assign(7)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

In [ ]:
#try .assign
changeable_tensor[0].assign(7)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

# creating random tensors
random tensors are tensors of some arbitrary size wich contains randoms numbers


In [ ]:
#create two random (but same tensors) tensors
import tensorflow as tf

random_1 = tf.random.Generator.from_seed(42)
tensor_1 = random_1.normal(shape=(3, 2))
print("Tensor 1:")
print(tensor_1)

random_2 = tf.random.Generator.from_seed(42)
tensor_2 = random_2.normal(shape=(3,2))
print("Tensor 2:")
print(tensor_2)

tensor_1 ==  tensor_2
# cambiando il seed per entrambi avendo lo stesso valore gli array saranno completamente  uguali

Tensor 1:
tf.Tensor(
[[-0.7565803  -0.06854702]
 [ 0.07595026 -1.2573844 ]
 [-0.23193765 -1.8107855 ]], shape=(3, 2), dtype=float32)
Tensor 2:
tf.Tensor(
[[-0.7565803  -0.06854702]
 [ 0.07595026 -1.2573844 ]
 [-0.23193765 -1.8107855 ]], shape=(3, 2), dtype=float32)


<tf.Tensor: shape=(3, 2), dtype=bool, numpy=
array([[ True,  True],
       [ True,  True],
       [ True,  True]])>

##shuffle the order of elements in  a tensor

In [ ]:
##shuffle the order of elements in  a tensor
not_shuffled = tf.constant([[10,7],[3,4],[2,5]])
#shuffle our non-shuffled tensor
tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 3,  4],
       [10,  7],
       [ 2,  5]], dtype=int32)>

In [ ]:

not_shuffled = tf.constant([[10,7],[3,4],[2,5]])
tf.random.set_seed(42)#global seed
tf.random.shuffle(not_shuffled, seed = 42)#operational seed

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]], dtype=int32)>

### other way to create tensors

In [ ]:
#create tensor with all 1
tensors_numPy = tf.ones([10,7])
print(tensors_numPy)

tf.Tensor(
[[1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]], shape=(10, 7), dtype=float32)


In [ ]:
#create tensors with all 0
tensors_numPy0= tf.zeros([10,7])
print(tensors_numPy0)
tensors_numPyZero = tf.zeros(shape =(3,4))# create a tuple
print(tensors_numPyZero)

tf.Tensor(
[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]], shape=(10, 7), dtype=float32)
tf.Tensor(
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]], shape=(3, 4), dtype=float32)


### turns numpy arrays into tensors
the main difference between numpy arrays and tensorflow tensors is that tensors
can be run on a gpu (much faster for numerical computing)

In [ ]:
# you can also turn numpy arrays into tensors
import numpy as np

numpy_A = np.arange(1,25,dtype= np.int32)
numpy_A
#x = tf.constant(some_matrix)
#y = tf.constant(vector)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [ ]:
## covert to a tensor from numpy
## same constant just different shape the shape in this case make change also the dimension
A = tf.constant(numpy_A, shape=(2,3,4)) #modifying shape
print(A)
B = tf.constant(numpy_A)
print(B)
print(f' {A.ndim}  this is the shape changed dimension')
print( f' {B.ndim}  this is the not changed dimension')

tf.Tensor(
[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]], shape=(2, 3, 4), dtype=int32)
tf.Tensor([ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24], shape=(24,), dtype=int32)
 3  this is the shape changed dimension
 1  this is the not changed dimension


## getting information from tensors
attributes
 * shapes
 * ranks
 * Axis or dimensions
 * size


In [ ]:
## getting info from tensors
##  crete a tensor of rank 4
rank_4_dim = tf.zeros([ 2,3,4,5,])
rank_4_dim

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [ ]:

## how to get the information from tensors
rank_4_dim.shape, rank_4_dim.ndim, tf.size(rank_4_dim)

(TensorShape([2, 3, 4, 5]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=120>)

In [ ]:
## get various attributes of out tensors
print("Datatype of every element:", rank_4_dim.dtype)
print("Number od dimensions(rank):", rank_4_dim.ndim)
print("Shape of tensor:",rank_4_dim.shape)
print("Elements along the 0 axis:", rank_4_dim.shape[0])
print("Elements along the last axis:", rank_4_dim.shape[-1])
print("total number of elements in out tensor:",tf.size(rank_4_dim))
print("total number of elements in out tensor:",tf.size(rank_4_dim).numpy())

Datatype of every element: <dtype: 'float32'>
Number od dimensions(rank): 4
Shape of tensor: (2, 3, 4, 5)
Elements along the 0 axis: 2
Elements along the last axis: 5
total number of elements in out tensor: tf.Tensor(120, shape=(), dtype=int32)
total number of elements in out tensor: 120


In [ ]:
rank_4_dim[:2,:2,:2,:2]
#get the first two elements of each dimensions
#get the differente dimension
rank_4_dim[:2,:,:2,:2]#this way u will see just 3 of the 4  dimension

<tf.Tensor: shape=(2, 3, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [ ]:
# create a rank  2 tensor  (2dimension)

rank_2_tensor= tf.constant([[10,7],[3,4],[2,5]])
rank_2_tensor.ndim
rank_2_tensor[:,-1]

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([7, 4, 5], dtype=int32)>

In [ ]:
# add an extra dimension
rank_3_tensor = rank_2_tensor[...,tf.newaxis]
rank_3_tensor

<tf.Tensor: shape=(3, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]],

       [[ 2],
        [ 5]]], dtype=int32)>

In [ ]:
tf.expand_dims(rank_2_tensor,axis=-1)# '-1' means expand the final axis


<tf.Tensor: shape=(3, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]],

       [[ 2],
        [ 5]]], dtype=int32)>

manipulating tensors with basics operations
basic operations:
 `+` `-` `/` `*`

In [ ]:
# adding a number out tensor
tensor = tf.constant([[10,5],[5,3]])
print(tensor +10)
## but the tensor is unchanged
print(tensor)
#use the tf builtin  functions
print(tf.multiply(tensor,10))

tf.Tensor(
[[20 15]
 [15 13]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[10  5]
 [ 5  3]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[100  50]
 [ 50  30]], shape=(2, 2), dtype=int32)


## metrix moltiplications
in machine learnig, matrix multiplications is one of the most common in tensor operations

In [ ]:
print(tensor)
result = tf.matmul(tensor,tensor)
result

tf.Tensor(
[[10  5]
 [ 5  3]], shape=(2, 2), dtype=int32)


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[125,  65],
       [ 65,  34]], dtype=int32)>

In [ ]:
t = tf.constant([[1,0,2],[2,1,3],[1,0,4]])
f = tf.constant([[2,6,1],[5,7,8],[4,8,1]])
res= tf.matmul(t,f)
print(res)
## if they have differente shapes this will not work

## create tensor of different shapes


tf.Tensor(
[[10 22  3]
 [21 43 13]
 [18 38  5]], shape=(3, 3), dtype=int32)


In [ ]:
tf.tensordot(tf.transpose(t),f,axes=1 )
# transpose  cambia l ordine del tensor e reshape ne camibia lo shape
#perform matrix multiplication between t , f (transposed)
tf.matmul(t,tf.transpose(f))
#perform matrix mul between t,f (reshaped)
tf.matmul(t ,tf.reshape(f,shape= (3,3)))


<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[10, 22,  3],
       [21, 43, 13],
       [18, 38,  5]], dtype=int32)>

## changing datatypeof a tensor
puoi cabiare in  float e viceversa semplicemente specificando con tf.cast( nometensorCheVuoiCambiare, il valoreCheVuoiAssegnare) sotto trovi gli esempi bambola

In [ ]:
# creting a tensor with default datatype
B= tf.constant ([1.7,7.4])
B.dtype

tf.float32

In [ ]:
C = tf.constant([7,10])
C.dtype

tf.int32

In [ ]:
# change from float 32 to 16 bit precision tensor
B = tf.cast(B, dtype=tf.float16)
B

<tf.Tensor: shape=(2,), dtype=float16, numpy=array([1.7, 7.4], dtype=float16)>

##Aggregation tensors
aggregazione dei tensor = da  diversi valori condensarli in valori piu piccoli


In [ ]:
# getting the absolute values
D = tf.constant([-7,-10])
print(D)
print(tf.abs(D))# nuovo metodo che li rende positivi ritornado in numero assoluto

tf.Tensor([ -7 -10], shape=(2,), dtype=int32)
tf.Tensor([ 7 10], shape=(2,), dtype=int32)


* ricevere il massimo
* il minomo di un tensor
* find the mean of a tensor
* get the sum of a tensor

In [ ]:
# crate a ransom tensor with a values between 0 and 100 of size 50
E = tf.constant(np.random.randint(0, 100, size = 50))
print(E)
# find a minimum
minimum = tf.reduce_min(E)## trovi il minimo del tensor
print(minimum)
maximum = tf.reduce_max(E)
print(maximum)
#find the mean
mean = tf.reduce_mean(E) # trovi la media
print(mean)
sum = tf.reduce_sum(E)# trovi la somma di un tensor
print(sum)
var = tf.cast(E,dtype=tf.float64)# importante per trovare il variance e STD bisogna che il nostro input sia float e not int
#per questo lo trsformiamo
variance =tf.math.reduce_variance(var)
print(variance)
standard_dev = tf.math.reduce_std(var)#standard_deviation
print(standard_dev)# radice quadrata di variace

tf.Tensor(
[74 45 88 29 53 56  8 40 60 48 38 76 17 12 67 86 70  4 25 88 47  2 55  8
 98 70 47 42 91 48  4 23 24 42  0 34 83  1 88 38 19  4 34 28  1  8  0 29
 94 69], shape=(50,), dtype=int64)
tf.Tensor(0, shape=(), dtype=int64)
tf.Tensor(98, shape=(), dtype=int64)
tf.Tensor(42, shape=(), dtype=int64)
tf.Tensor(2115, shape=(), dtype=int64)
tf.Tensor(885.21, shape=(), dtype=float64)
tf.Tensor(29.75247888832122, shape=(), dtype=float64)


## find the positional maximum and minimum

In [ ]:
# create a new tensor to find the positional maximum an minimum
tf.random.set_seed(42)
F = tf.random.uniform(shape=[50])
print(F)



#find the maximum positional
ma = tf.argmax(F)
print(ma)#position
# index of our largest position
print(F[tf.argmax(F)])# il numero in questione


#find the positional minimum
mi = tf.argmin(F)
print(mi)
print(F[tf.argmin(F)])


tf.Tensor(
[0.6645621  0.44100678 0.3528825  0.46448255 0.03366041 0.68467236
 0.74011743 0.8724445  0.22632635 0.22319686 0.3103881  0.7223358
 0.13318717 0.5480639  0.5746088  0.8996835  0.00946367 0.5212307
 0.6345445  0.1993283  0.72942245 0.54583454 0.10756552 0.6767061
 0.6602763  0.33695042 0.60141766 0.21062577 0.8527372  0.44062173
 0.9485276  0.23752594 0.81179297 0.5263394  0.494308   0.21612847
 0.8457197  0.8718841  0.3083862  0.6868038  0.23764038 0.7817228
 0.9671384  0.06870162 0.79873943 0.66028714 0.5871513  0.16461694
 0.7381023  0.32054043], shape=(50,), dtype=float32)
tf.Tensor(42, shape=(), dtype=int64)
tf.Tensor(0.9671384, shape=(), dtype=float32)
tf.Tensor(16, shape=(), dtype=int64)
tf.Tensor(0.009463668, shape=(), dtype=float32)


## Squeezing a tensor removing all single dimension


In [ ]:
tf.random.set_seed(42)
G = tf.constant(tf.random.uniform(shape=[50]),shape = (1,1,1,1,50))
print(G)
squeeze = tf.squeeze(G)
print(squeeze)

tf.Tensor(
[[[[[0.6645621  0.44100678 0.3528825  0.46448255 0.03366041 0.68467236
     0.74011743 0.8724445  0.22632635 0.22319686 0.3103881  0.7223358
     0.13318717 0.5480639  0.5746088  0.8996835  0.00946367 0.5212307
     0.6345445  0.1993283  0.72942245 0.54583454 0.10756552 0.6767061
     0.6602763  0.33695042 0.60141766 0.21062577 0.8527372  0.44062173
     0.9485276  0.23752594 0.81179297 0.5263394  0.494308   0.21612847
     0.8457197  0.8718841  0.3083862  0.6868038  0.23764038 0.7817228
     0.9671384  0.06870162 0.79873943 0.66028714 0.5871513  0.16461694
     0.7381023  0.32054043]]]]], shape=(1, 1, 1, 1, 50), dtype=float32)
tf.Tensor(
[0.6645621  0.44100678 0.3528825  0.46448255 0.03366041 0.68467236
 0.74011743 0.8724445  0.22632635 0.22319686 0.3103881  0.7223358
 0.13318717 0.5480639  0.5746088  0.8996835  0.00946367 0.5212307
 0.6345445  0.1993283  0.72942245 0.54583454 0.10756552 0.6767061
 0.6602763  0.33695042 0.60141766 0.21062577 0.8527372  0.44062173
 0.9485276

## One-hote encoding

In [ ]:
#create a list o indicies
some_list = [1,2,3,4]
tf.one_hot(some_list, depth=4)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.]], dtype=float32)>

In [ ]:
tf.config.list_physical_devices("GPU")

[PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

In [ ]:
!nvidia-smi

Fri Jul 26 20:51:01 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   56C    P0              30W /  70W |    107MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

 ## esempi di scalar vector matrix Tensor

x = tf.constant(5)
print(x)
Scalar: A scalar is a single value, represented as a 0-dimensional tensor. It has no indices or axes. In TensorFlow, a scalar is represented as a tf.Tensor with shape ().



Vector: A vector is a 1-dimensional array of values, represented as a 1-dimensional tensor. It has one index or axis. In TensorFlow, a vector is represented as a tf.Tensor with shape (n,), where n is the number of elements in the vector.

Example: x = tf.constant([1, 2, 3, 4, 5]) is a vector tensor with shape (5,).

Matrix: A matrix is a 2-dimensional array of values, represented as a 2-dimensional tensor. It has two indices or axes. In TensorFlow, a matrix is represented as a tf.Tensor with shape (m, n), where m is the number of rows and n is the number of columns.

Example: x = tf.constant([[1, 2], [3, 4]]) is a matrix tensor with shape (2, 2).

Tensor: A tensor is a multi-dimensional array of values, represented as a tensor with three or more indices or axes. In TensorFlow, a tensor is represented as a tf.Tensor with shape (m, n, o, ...), where m, n, o, etc. are the number of elements in each dimension.

Example: x = tf.constant([[[1, 2], [3, 4]], [[5, 6], [7, 8]]]) is a tensor with shape (2, 2, 2).

In [ ]:
W = tf.constant(10)
print(W)
print( tf.rank(W))


tf.Tensor(10, shape=(), dtype=int32)
tf.Tensor(0, shape=(), dtype=int32)


In [ ]:
tf.random.set_seed(42)
Zero = tf.random.uniform(shape=([5,300]))
print(Zero)
One = tf.random.uniform(shape=([5,300]))
print(One)
one_transposed = tf.transpose(One)
print(one_transposed)
result = tf.matmul(Zero,one_transposed)
print(result)
res= tf.tensordot(Zero,one_transposed,axes=1)
print(res)

tf.Tensor(
[[0.6645621  0.44100678 0.3528825  ... 0.31410468 0.7593535  0.03699052]
 [0.532024   0.29129946 0.10571766 ... 0.54052293 0.31425726 0.2200619 ]
 [0.08404207 0.03614604 0.97732127 ... 0.21516645 0.9786098  0.00726748]
 [0.7396945  0.6653172  0.0787828  ... 0.7117733  0.07013571 0.9409125 ]
 [0.15861344 0.12024033 0.27218235 ... 0.8824879  0.1432488  0.44135118]], shape=(5, 300), dtype=float32)
tf.Tensor(
[[0.68789124 0.48447883 0.9309944  ... 0.6920762  0.33180213 0.9212563 ]
 [0.27369928 0.10631859 0.6218617  ... 0.4382149  0.30427706 0.51477313]
 [0.00920248 0.37280262 0.8177401  ... 0.56786287 0.49201214 0.9892651 ]
 [0.88608265 0.08672249 0.12160683 ... 0.91770685 0.72545695 0.8280058 ]
 [0.36690474 0.9200133  0.9646884  ... 0.69012    0.7137332  0.2584542 ]], shape=(5, 300), dtype=float32)
tf.Tensor(
[[0.68789124 0.27369928 0.00920248 0.88608265 0.36690474]
 [0.48447883 0.10631859 0.37280262 0.08672249 0.9200133 ]
 [0.9309944  0.6218617  0.8177401  0.12160683 0.9646884

In [ ]:
te = tf.random.uniform(shape=([244,244,3]))
print(te,)


tf.Tensor(
[[[0.7413678  0.62854624 0.01738465]
  [0.3431449  0.51063764 0.3777541 ]
  [0.07321596 0.02137029 0.2871771 ]
  ...
  [0.46217704 0.8177172  0.9324174 ]
  [0.3542608  0.8056662  0.04422152]
  [0.21755838 0.4517957  0.48437166]]

 [[0.03183556 0.3801626  0.06121147]
  [0.3073603  0.7837498  0.66695607]
  [0.36168587 0.8880923  0.8694893 ]
  ...
  [0.7105495  0.20656955 0.95012224]
  [0.8192378  0.5350205  0.29332328]
  [0.08032727 0.10789704 0.13451433]]

 [[0.30395794 0.70867944 0.02875113]
  [0.851349   0.75918424 0.9711982 ]
  [0.2049936  0.07748234 0.6421211 ]
  ...
  [0.4341513  0.57926345 0.38649082]
  [0.6188736  0.00327778 0.05403554]
  [0.96550107 0.17174828 0.39154875]]

 ...

 [[0.56169426 0.998615   0.00484431]
  [0.78096175 0.40864944 0.783298  ]
  [0.09273458 0.16288245 0.6635208 ]
  ...
  [0.23279548 0.01078749 0.7668377 ]
  [0.95119536 0.41704285 0.29609716]
  [0.9946232  0.28444266 0.95502865]]

 [[0.89764655 0.41565382 0.81090987]
  [0.74238694 0.74139726 0

In [ ]:
print(tf.argmax(te,axis=0))
print(tf.argmin(te,axis=0))
print(te)


tf.Tensor(
[[ 88 241  93]
 [118  76  68]
 [104  87  17]
 [198  85 114]
 [128  41 156]
 [ 40  69 111]
 [203 237 231]
 [201 189  27]
 [  2 156 138]
 [139  27  55]
 [182  17 144]
 [229  75 192]
 [ 48  50   3]
 [ 67 126 237]
 [108  22 201]
 [125  60 214]
 [177 176  88]
 [ 70  88 150]
 [181  93 200]
 [207 205 203]
 [ 55 191 222]
 [ 58 147 110]
 [ 26 108 103]
 [166  33 164]
 [ 35  89 216]
 [184 194  97]
 [ 36 192 243]
 [ 64  94 155]
 [103 193 173]
 [185 156 222]
 [ 16 136  36]
 [231  96 143]
 [163 158  77]
 [ 10 112 182]
 [ 32  57  16]
 [135  84  25]
 [128  17 158]
 [138 227  45]
 [ 23  43 153]
 [  9  72  27]
 [131  53 165]
 [  8 120 243]
 [153  34 225]
 [ 13  49 127]
 [107  15 138]
 [135 176  81]
 [ 78  71  55]
 [236  73 198]
 [124  24 118]
 [228 175 190]
 [195  71 118]
 [ 42  14 194]
 [207 146 170]
 [121 106  88]
 [ 57 134 192]
 [226 218   1]
 [ 45  87  94]
 [196 178 198]
 [ 18   0 188]
 [ 56 221 133]
 [123 172 208]
 [ 90 113   3]
 [142  86   2]
 [ 10  42  16]
 [198 196  30]
 [ 20 142 120]